-- totall number of customers by countries :


select 
country ,
count ( customer_key ) as totall_customer 

from gold.dim_customers
group by country 
order by count ( customer_key ) desc


--totall customers by gender :


select 
gender,
count ( customer_key ) as totall_customer 

from gold.dim_customers
group by gender 
order by count ( customer_key ) desc

-- totall products by category :

select 
category ,
count(product_key ) as totall_product 

from gold.dim_products
group by category 
order by count(product_key ) desc


--avrage costs in each category :

select 
category ,
avg( cost ) as avg_cost

from gold.dim_products
group by category 
order by avg( cost ) desc


--total revenue generated for each category :

select
dp.category ,
sum(fs.sales_amount) as totall_revenue 

from gold.dim_products as dp
left join gold.facts_sales as fs
on dp.product_key = fs.product_key
group by dp.category 
order by totall_revenue desc


-- totall revenue generated by each customer :

select
fs.customer_key , 
coalesce(trim(dc.first_name),'') +' '+coalesce(trim(dc.last_name),'') as full_name,
sum(fs.sales_amount) as totall_revenue 

from gold.facts_sales as fs
left join gold.dim_customers as dc
on fs.customer_key = dc.customer_key
group by coalesce(trim(dc.first_name),'') +' '+coalesce(trim(dc.last_name),'') ,fs.customer_key
order by sum(fs.sales_amount) desc


--distribution of sold item accross counties :


select 

count (fs.product_key ) as sold_items , 
dc.country


from gold.facts_sales as fs
left join gold.dim_customers as dc
on fs.customer_key = dc.customer_key

group by dc.country
order by count (fs.product_key ) desc


